string token # A unique ID representing the sender

string block_id # ID of the block that was created
string xml # The XML of the new element

---
bool success # Indicate successful run of triggered service
string message # Informational, e.g. for error messages