# Make a new project even if it would result in data loss
bool force

---

# True if a new project was created, otherwise false
bool success

# An error message describing what went wrong
string message
