# The name of the project to perform the operation on
string name

# Perfrom the operation even if it would result in data loss
bool force

---

# True if the service completed successfully, false if there was an error
bool success

# Predefined reason codes
string ERR_PROJECT_EXISTS=project_exists
string ERR_NO_SUCH_PROJECT=no_such_project
string ERR_UNSAVED_CHANGES=unsaved_changes
string ERR_UNKOWN=unknown

# A short string defining the type of error that occurred
string reason

# A human-readable English error message describing what went wrong
string message
