bool result # Whether the user pressed OK or cancel
string prompt_id # The unique ID prepresenting the prompt
string value # The value returned by the prompt
---
bool success # Whether the service call failed or not
string message # A desscriptive error message is success is false
